#!/usr/bin/env python

"""Starts windshape drone and fans array control with GUI.

The parameters used will be the one of intel.yaml in config folder.

Allow user to have a visual feedback of the drone state and to change
parameters in real time.

Usage: "roslaunch windshape control.launch node:=gui"
"""

import sys

from PyQt5.QtWidgets import QApplication

# ROS main library
import rospy

# Package
import windshape

# Initializes node
rospy.init_node('test_drone', anonymous=True, log_level=rospy.INFO)

# Creates App
app = QApplication(['Drone control'])

# Main widget with all interface
mainWindow = windshape.UserInterface()

# Exits after closing window
sys.exit(app.exec_())
