#!/usr/bin/env python

import sys

from PyQt5.QtWidgets import QApplication

import rospy

from windshape import UserInterface

# Initializes node
rospy.init_node('test_drone', anonymous=True, log_level=rospy.INFO)
rospy.sleep(1.0)

# Creates App
app = QApplication(['Drone control'])

# Main window
mainWindow = UserInterface()

# Exit after closing window
sys.exit(app.exec_())
