#!/usr/bin/env python

"""Starts windshape drone and fans array control.

The parameters used will be the one of intel.yaml in config folder.

Node used for windshape drone control and fans array communication.

Usage: "roslaunch windshape control.launch"
"""

import sys

# ROS main library
import rospy

# Package
import windshape

# Initializes node
rospy.init_node('test_drone', anonymous=True, log_level=rospy.DEBUG)

# With GUI
if rospy.get_param('~gui'):
	
	# Creates App
	from PyQt5.QtWidgets import QApplication
	app = QApplication(['Drone control'])

	# Main widget with all interface
	mainWindow = windshape.UserInterface()

	# Exits after closing window
	sys.exit(app.exec_())

# Without GUI
else:
	
	# Drone control and fans array communication
	commander = windshape.Commander()

	# Press Ctrl+C to quit
	rospy.spin()
