# vrpn_client_ros configuration

# Process incoming VRPN data (Hz)
update_frequency: 100.0

# Auto-detect new VRPN Trackers (Hz)
refresh_tracker_frequency: 1.0

# List of VRPN Trackers to expect if previous parameter is set to 0
trackers: []

# Frame id of the messages
frame_id: "world"

# Use VRPN server time instead of ROS time
use_server_time: false

# Braodcast on /tf
broadcast_tf: false
