#!/usr/bin/env python

"""Plots a log file of a windshape run.

Files are stored under windshape/src/windshape/log/files.

Usage: rosrun windshape replay
"""

import os
import sys

from PyQt5.QtWidgets import QApplication

# Package
import windshape

# Creates App
app = QApplication(['Replay'])

# Replay window
replay = windshape.Replay()

# Exits after closing window
sys.exit(app.exec_())
